# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\x12\x04game\"\xaa\x01\n\x04Game\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tcover_url\x18\x03 \x01(\t\x12\x0c\n\x04lang\x18\x04 \x01(\t\x12\r\n\x05intro\x18\x05 \x01(\t\x12\x12\n\nbackground\x18\x06 \x01(\t\x12\x11\n\tgame_tags\x18\x07 \x03(\t\x12\x11\n\tmechanics\x18\x08 \x01(\t\x12\x19\n\x11\x62\x61\x63kground_musics\x18\t \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GAME']._serialized_start=21
  _globals['_GAME']._serialized_end=191
# @@protoc_insertion_point(module_scope)
